### Đăng ký
POST http://localhost/book_store/api/register.php
Content-Type: application/json

{
  "name": "Nguyen Van A",
  "email": "a@example.com",
  "password": "123456"
}

### Đăng nhập
POST http://localhost/book_store/api/login.php
Content-Type: application/json

{
  "email": "a@example.com",
  "password": "123456"
}

### Lấy danh sách thể loại
GET http://localhost/book_store/api/category.php

### Thêm thể loại
POST http://localhost/book_store/api/category.php
Content-Type: application/json

{
  "name": "Tâm lý học",
  "description": "Sách phát triển bản thân và tâm lý"
}
